exports.trad = {
	"ability": [
		{"en": "adaptability", "it": "adattabilità"},
		{"en": "aerilate", "it": "pellecielo"},
		{"en": "aftermath", "it": "scoppio"},
		{"en": "air lock", "it": "riparo"},
		{"en": "analytic", "it": "ponderazione"},
		{"en": "anger point", "it": "grancollera"},
		{"en": "anticipation", "it": "presagio"},
		{"en": "arena trap", "it": "trappoarena"},
		{"en": "aroma veil", "it": "aromavelo"},
		{"en": "aura break", "it": "frangiaura"},
		{"en": "bad dreams", "it": "sogniamari"},
		{"en": "battle armor", "it": "lottascudo"},
		{"en": "big pecks", "it": "pettinfuori"},
		{"en": "blaze", "it": "aiutofuoco"},
		{"en": "bulletproof", "it": "antiproiettile"},
		{"en": "cheek pouch", "it": "guancegonfie"},
		{"en": "chlorophyll", "it": "clorofilla"},
		{"en": "clear body", "it": "corpochiaro"},
		{"en": "cloud nine", "it": "antimeteo"},
		{"en": "color change", "it": "cambiacolore"},
		{"en": "competitive", "it": "tenacia"},
		{"en": "compoundeyes", "it": "insettocchi"},
		{"en": "contrary", "it": "inversione"},
		{"en": "cursed body", "it": "corpofunesto"},
		{"en": "cute charm", "it": "incantevole"},
		{"en": "damp", "it": "umidità"},
		{"en": "dark aura", "it": "auratetra"},
		{"en": "defeatist", "it": "sconforto"},
		{"en": "defiant", "it": "agonismo"},
		{"en": "delta stream", "it": "flusso delta"},
		{"en": "desolate land", "it": "terra estrema"},
		{"en": "download", "it": "download"},
		{"en": "drizzle", "it": "piovischio"},
		{"en": "drought", "it": "siccità"},
		{"en": "dry skin", "it": "pellearsa"},
		{"en": "early bird", "it": "sveglialampo"},
		{"en": "effect spore", "it": "spargispora"},
		{"en": "fairy aura", "it": "aurafolletto"},
		{"en": "filter", "it": "filtro"},
		{"en": "flame body", "it": "corpodifuoco"},
		{"en": "flare boost", "it": "bruciaimpeto"},
		{"en": "flash fire", "it": "fuocardore"},
		{"en": "flower gift", "it": "regalfiore"},
		{"en": "flower veil", "it": "fiorvelo"},
		{"en": "forecast", "it": "previsioni"},
		{"en": "forewarn", "it": "premonizione"},
		{"en": "friend guard", "it": "amicoscudo"},
		{"en": "frisk", "it": "indagine"},
		{"en": "fur coat", "it": "foltopelo"},
		{"en": "gale wings", "it": "aliraffica"},
		{"en": "gluttony", "it": "voracità"},
		{"en": "gooey", "it": "viscosità"},
		{"en": "grass pelt", "it": "peloderba"},
		{"en": "guts", "it": "dentistretti"},
		{"en": "harvest", "it": "coglibacche"},
		{"en": "healer", "it": "curacuore"},
		{"en": "heatproof", "it": "antifuoco"},
		{"en": "heavy metal", "it": "metalpesante"},
		{"en": "honey gather", "it": "mielincetta"},
		{"en": "huge power", "it": "macroforza"},
		{"en": "hustle", "it": "tuttafretta"},
		{"en": "hydration", "it": "idratazione"},
		{"en": "hyper cutter", "it": "ipertaglio"},
		{"en": "ice body", "it": "corpogelo"},
		{"en": "illuminate", "it": "illumina"},
		{"en": "illusion", "it": "illusione"},
		{"en": "immunity", "it": "immunità"},
		{"en": "imposter", "it": "sosia"},
		{"en": "infiltrator", "it": "intrapasso"},
		{"en": "inner focus", "it": "fuocodentro"},
		{"en": "insomnia", "it": "insonnia"},
		{"en": "intimidate", "it": "prepotenza"},
		{"en": "iron barbs", "it": "spineferrate"},
		{"en": "iron fist", "it": "ferropugno"},
		{"en": "justified", "it": "giustizia"},
		{"en": "keen eye", "it": "sguardofermo"},
		{"en": "klutz", "it": "impaccio"},
		{"en": "leaf guard", "it": "fogliamanto"},
		{"en": "levitate", "it": "levitazione"},
		{"en": "light metal", "it": "metalleggero"},
		{"en": "lightningrod", "it": "parafulmine"},
		{"en": "limber", "it": "scioltezza"},
		{"en": "liquid ooze", "it": "melma"},
		{"en": "magic bounce", "it": "magispecchio"},
		{"en": "magic guard", "it": "magicscudo"},
		{"en": "magician", "it": "prestigiatore"},
		{"en": "magma armor", "it": "magmascudo"},
		{"en": "magnet pull", "it": "magnetismo"},
		{"en": "marvel scale", "it": "pelledura"},
		{"en": "mega launcher", "it": "megalancio"},
		{"en": "minus", "it": "meno"},
		{"en": "mold breaker", "it": "rompiforma"},
		{"en": "moody", "it": "altalena"},
		{"en": "motor drive", "it": "elettrorapid"},
		{"en": "moxie", "it": "arroganza"},
		{"en": "multiscale", "it": "multisquame"},
		{"en": "multitype", "it": "multitipo"},
		{"en": "mummy", "it": "mummia"},
		{"en": "natural cure", "it": "alternacura"},
		{"en": "no guard", "it": "nullodifesa"},
		{"en": "normalize", "it": "normalità"},
		{"en": "oblivious", "it": "indifferenza"},
		{"en": "overcoat", "it": "copricapo"},
		{"en": "overgrow", "it": "erbaiuto"},
		{"en": "own tempo", "it": "mente locale"},
		{"en": "parental bond", "it": "amorefiliale"},
		{"en": "pickpocket", "it": "arraffalesto"},
		{"en": "pickup", "it": "raccolta"},
		{"en": "plus", "it": "più"},
		{"en": "pixilate", "it": "pellefolletto"},
		{"en": "poison heal", "it": "velencura"},
		{"en": "poison point", "it": "velenopunto"},
		{"en": "poison touch", "it": "velentocco"},
		{"en": "prankster", "it": "burla"},
		{"en": "pressure", "it": "pressione"},
		{"en": "primordial sea", "it": "mare primordiale"},
		{"en": "protean", "it": "mutatipo"},
		{"en": "pure power", "it": "forzapura"},
		{"en": "quick feet", "it": "piedisvelti"},
		{"en": "rain dish", "it": "copripioggia"},
		{"en": "rattled", "it": "paura"},
		{"en": "reckless", "it": "temerarietà"},
		{"en": "refrigerate", "it": "pellegelo"},
		{"en": "regenerator", "it": "rigenergia"},
		{"en": "rivalry", "it": "antagonismo"},
		{"en": "rock head", "it": "testadura"},
		{"en": "rough skin", "it": "cartavetro"},
		{"en": "run away", "it": "fugafacile"},
		{"en": "sand force", "it": "silicoforza"},
		{"en": "sand rush", "it": "remasabbia"},
		{"en": "sand stream", "it": "sabbia fiume"},
		{"en": "sand veil", "it": "sabbiavelo"},
		{"en": "sap sipper", "it": "mangiaerba"},
		{"en": "scrappy", "it": "nervisaldi"},
		{"en": "serene grace", "it": "leggiadro"},
		{"en": "shadow tag", "it": "pedinombra"},
		{"en": "shed skin", "it": "muta"},
		{"en": "sheer force", "it": "forzabruta"},
		{"en": "shell armor", "it": "guscioscudo"},
		{"en": "shield dust", "it": "polvoscudo"},
		{"en": "simple", "it": "disinvoltura"},
		{"en": "skill link", "it": "abillegame"},
		{"en": "slow start", "it": "lentoinizio"},
		{"en": "sniper", "it": "cecchino"},
		{"en": "snow cloak", "it": "mantelneve"},
		{"en": "snow warning", "it": "scendineve"},
		{"en": "solar power", "it": "solarpotere"},
		{"en": "solid rock", "it": "solidroccia"},
		{"en": "soundproof", "it": "antisuono"},
		{"en": "speed boost", "it": "acceleratore"},
		{"en": "stall", "it": "rallentatore"},
		{"en": "stance change", "it": "accendilotta"},
		{"en": "static", "it": "statico"},
		{"en": "steadfast", "it": "cuordeciso"},
		{"en": "stench", "it": "tanfo"},
		{"en": "sticky hold", "it": "antifurto"},
		{"en": "storm drain", "it": "acquascolo"},
		{"en": "strong jaw", "it": "ferromascella"},
		{"en": "sturdy", "it": "vigore"},
		{"en": "suction cups", "it": "ventose"},
		{"en": "super luck", "it": "supersorte"},
		{"en": "swarm", "it": "aiutinsetto"},
		{"en": "sweet veil", "it": "dolcevelo"},
		{"en": "swift swim", "it": "nuotovelox"},
		{"en": "symbiosis", "it": "simbiosi"},
		{"en": "synchronize", "it": "sincronismo"},
		{"en": "tangled feet", "it": "intricopiedi"},
		{"en": "technician", "it": "tecnico"},
		{"en": "telepathy", "it": "telepatia"},
		{"en": "teravolt", "it": "teravolt"},
		{"en": "thick fat", "it": "grassospesso"},
		{"en": "tinted lens", "it": "lentifumé"},
		{"en": "torrent", "it": "acquaiuto"},
		{"en": "tough claws", "it": "unghiedure"},
		{"en": "toxic boost", "it": "velenimpeto"},
		{"en": "trace", "it": "traccia"},
		{"en": "truant", "it": "pigrone"},
		{"en": "turboblaze", "it": "piroturbina"},
		{"en": "unaware", "it": "imprudenza"},
		{"en": "unburden", "it": "agiltecnica"},
		{"en": "unnerve", "it": "agitazione"},
		{"en": "victory star", "it": "tinovictoria"},
		{"en": "vital spirit", "it": "spiritovivo"},
		{"en": "volt absorb", "it": "assorbivolt"},
		{"en": "water absorb", "it": "assorbiacqua"},
		{"en": "water veil", "it": "idrovelo"},
		{"en": "weak armor", "it": "sottilguscio"},
		{"en": "white smoke", "it": "fumochiaro"},
		{"en": "wonder guard", "it": "magidifesa"},
		{"en": "wonder skin", "it": "splendicute"},
		{"en": "zen mode", "it": "stato zen"}
	],
	"move": [
		{"en": "absorb", "it": "assorbimento"},
		{"en": "acid armor", "it": "scudo acido"},
		{"en": "acid spray", "it": "acidobomba"},
		{"en": "acid", "it": "acido"},
		{"en": "acrobatics", "it": "acrobazia"},
		{"en": "acupressure", "it": "acupressione"},
		{"en": "aerial ace", "it": "aeroassalto"},
		{"en": "aeroblast", "it": "aerocolpo"},
		{"en": "after you", "it": "cortesia"},
		{"en": "agility", "it": "agilità"},
		{"en": "air cutter", "it": "aerasoio"},
		{"en": "air slash", "it": "eterelama"},
		{"en": "ally switch", "it": "cambiaposto"},
		{"en": "amnesia", "it": "amnesia"},
		{"en": "ancient power", "it": "forzantica"},
		{"en": "aqua jet", "it": "acquagetto"},
		{"en": "aqua ring", "it": "acquanello"},
		{"en": "aqua tail", "it": "idrondata"},
		{"en": "arm thrust", "it": "sberletese"},
		{"en": "aromatherapy", "it": "aromaterapia"},
		{"en": "aromatic mist", "it": "nebularoma"},
		{"en": "assist", "it": "assistente"},
		{"en": "assurance", "it": "garanzia"},
		{"en": "astonish", "it": "sgomento"},
		{"en": "attack order", "it": "comandourto"},
		{"en": "attract", "it": "attrazione"},
		{"en": "aura sphere", "it": "forzasfera"},
		{"en": "aurora beam", "it": "raggiaurora"},
		{"en": "autotomize", "it": "sganciapesi"},
		{"en": "avalanche", "it": "slavina"},
		{"en": "baby-doll eyes", "it": "occhioni teneri"},
		{"en": "barrage", "it": "attacco pioggia"},
		{"en": "barrier", "it": "barriera"},
		{"en": "baton pass", "it": "staffetta"},
		{"en": "beat up", "it": "picchiaduro"},
		{"en": "belch", "it": "rutto"},
		{"en": "belly drum", "it": "panciamburo"},
		{"en": "bestow", "it": "cediregalo"},
		{"en": "bide", "it": "pazienza"},
		{"en": "bind", "it": "legatutto"},
		{"en": "bite", "it": "morso"},
		{"en": "blast burn", "it": "incendio"},
		{"en": "blaze kick", "it": "calciardente"},
		{"en": "blizzard", "it": "bora"},
		{"en": "block", "it": "blocco"},
		{"en": "blue flare", "it": "fuocoblu"},
		{"en": "body slam", "it": "corposcontro"},
		{"en": "bolt strike", "it": "lucesiluro"},
		{"en": "bone club", "it": "ossoclava"},
		{"en": "bone rush", "it": "ossoraffica"},
		{"en": "bonemerang", "it": "ossomerang"},
		{"en": "boomburst", "it": "ondaboato"},
		{"en": "bounce", "it": "rimbalzo"},
		{"en": "brave bird", "it": "baldeali"},
		{"en": "brick break", "it": "breccia"},
		{"en": "brine", "it": "acquadisale"},
		{"en": "bubble beam", "it": "bollaraggio"},
		{"en": "bubble", "it": "bolla"},
		{"en": "bug bite", "it": "coleomorso"},
		{"en": "bug buzz", "it": "ronzio"},
		{"en": "bulk up", "it": "granfisico"},
		{"en": "bulldoze", "it": "battiterra"},
		{"en": "bullet punch", "it": "pugnoscarica"},
		{"en": "bullet seed", "it": "semitraglia"},
		{"en": "calm mind", "it": "calmamente"},
		{"en": "camouflage", "it": "cammuffamento"},
		{"en": "captivate", "it": "incanto"},
		{"en": "celebrate", "it": "auguri"},
		{"en": "charge beam", "it": "raggioscossa"},
		{"en": "charge", "it": "sottocarica"},
		{"en": "charm", "it": "fascino"},
		{"en": "chatter", "it": "schiamazzo"},
		{"en": "chip away", "it": "insidia"},
		{"en": "circle throw", "it": "ribaltiro"},
		{"en": "clamp", "it": "tenaglia"},
		{"en": "clear smog", "it": "pulifumo"},
		{"en": "close combat", "it": "zuffa"},
		{"en": "coil", "it": "arrotola"},
		{"en": "comet punch", "it": "cometapugno"},
		{"en": "confide", "it": "confidenza"},
		{"en": "confuse ray", "it": "stordiraggio"},
		{"en": "confusion", "it": "confusione"},
		{"en": "constrict", "it": "limitazione"},
		{"en": "conversion 2", "it": "conversione2"},
		{"en": "conversion", "it": "conversione"},
		{"en": "copycat", "it": "copione"},
		{"en": "cosmic power", "it": "cosmoforza"},
		{"en": "cotton guard", "it": "cotonscudo"},
		{"en": "cotton spore", "it": "cottonspora"},
		{"en": "counter", "it": "contrattacco"},
		{"en": "covet", "it": "supplica"},
		{"en": "crabhammer", "it": "martellata"},
		{"en": "crafty shield", "it": "truccodifesa"},
		{"en": "cross chop", "it": "incrocolpo"},
		{"en": "cross poison", "it": "velenocroce"},
		{"en": "crunch", "it": "sgranocchio"},
		{"en": "crush claw", "it": "tritartigli"},
		{"en": "crush grip", "it": "sbriciolmano"},
		{"en": "curse", "it": "maledizione"},
		{"en": "cut", "it": "taglio"},
		{"en": "dark pulse", "it": "neropulsar"},
		{"en": "dark void", "it": "vuototetro"},
		{"en": "dazzling gleam", "it": "magibrillio"},
		{"en": "defend order", "it": "comandoscudo"},
		{"en": "defense curl", "it": "ricciolscudo"},
		{"en": "defog", "it": "scacciabruma"},
		{"en": "destiny bond", "it": "destinobbligato"},
		{"en": "detect", "it": "individua"},
		{"en": "dig", "it": "fossa"},
		{"en": "disable", "it": "inibitore"},
		{"en": "disarming voice", "it": "incantavoce"},
		{"en": "discharge", "it": "scarica"},
		{"en": "dive", "it": "sub"},
		{"en": "dizzy punch", "it": "stordipugno"},
		{"en": "doom desire", "it": "obbliderio"},
		{"en": "double hit", "it": "doppiosmash"},
		{"en": "double kick", "it": "doppiocalcio"},
		{"en": "double slap", "it": "doppiasberla"},
		{"en": "double team", "it": "doppioteam"},
		{"en": "double-edge", "it": "sdoppiatore"},
		{"en": "draco meteor", "it": "dragobolide"},
		{"en": "dragon ascent", "it": "ascesa del drago"},
		{"en": "dragon breath", "it": "dragospiro"},
		{"en": "dragon claw", "it": "dragartigli"},
		{"en": "dragon dance", "it": "dragodanza"},
		{"en": "dragon pulse", "it": "dragopulsar"},
		{"en": "dragon rage", "it": "ira di drago"},
		{"en": "dragon rush", "it": "dragofuria"},
		{"en": "dragon tail", "it": "codadrago"},
		{"en": "drain punch", "it": "assorbipugno"},
		{"en": "draining kiss", "it": "assorbibacio"},
		{"en": "dream eater", "it": "mangiasogni"},
		{"en": "drill peck", "it": "perforbecco"},
		{"en": "drill run", "it": "giravvita"},
		{"en": "dual chop", "it": "doppiocolpo"},
		{"en": "dynamic punch", "it": "dinamipugno"},
		{"en": "earth power", "it": "geoforza"},
		{"en": "earthquake", "it": "terremoto"},
		{"en": "echoed voice", "it": "echeggiavoce"},
		{"en": "eerie impulse", "it": "elettromistero"},
		{"en": "egg bomb", "it": "uovobomba"},
		{"en": "electric terrain", "it": "campo elettrico"},
		{"en": "electrify", "it": "elettrocontagio"},
		{"en": "electro ball", "it": "energisfera"},
		{"en": "electroweb", "it": "elettrotela"},
		{"en": "embargo", "it": "divieto"},
		{"en": "ember", "it": "braciere"},
		{"en": "encore", "it": "ripeti"},
		{"en": "endeavor", "it": "rimonta"},
		{"en": "endure", "it": "resistenza"},
		{"en": "energy ball", "it": "energipalla"},
		{"en": "entrainment", "it": "saltamicizia"},
		{"en": "eruption", "it": "eruzione"},
		{"en": "explosion", "it": "esplosione"},
		{"en": "extrasensory", "it": "extrasenso"},
		{"en": "extreme speed", "it": "extrarapido"},
		{"en": "facade", "it": "facciata"},
		{"en": "fairy lock", "it": "blocco fatato"},
		{"en": "fairy wind", "it": "vento di fata"},
		{"en": "fake out", "it": "bruciapelo"},
		{"en": "fake tears", "it": "falselacrime"},
		{"en": "false swipe", "it": "falsofinale"},
		{"en": "feather dance", "it": "danzadipiume"},
		{"en": "feint attack", "it": "finta"},
		{"en": "feint", "it": "fintoattacco"},
		{"en": "fell stinger", "it": "pungiglione"},
		{"en": "fiery dance", "it": "voldifuoco"},
		{"en": "final gambit", "it": "azzardo"},
		{"en": "fire blast", "it": "fuocobomba"},
		{"en": "fire fang", "it": "rogodenti"},
		{"en": "fire pledge", "it": "fiammapatto"},
		{"en": "fire punch", "it": "fuocopugno"},
		{"en": "fire spin", "it": "turbofuoco"},
		{"en": "fissure", "it": "abisso"},
		{"en": "flail", "it": "flagello"},
		{"en": "flame burst", "it": "pirolancio"},
		{"en": "flame charge", "it": "nitrocarica"},
		{"en": "flame wheel", "it": "ruotafuoco"},
		{"en": "flamethrower", "it": "lanciafiamme"},
		{"en": "flare blitz", "it": "fuococarica"},
		{"en": "flash cannon", "it": "cannonflash"},
		{"en": "flash", "it": "flash"},
		{"en": "flatter", "it": "adulazione"},
		{"en": "fling", "it": "lancio"},
		{"en": "flower shield", "it": "fiordifesa"},
		{"en": "fly", "it": "volo"},
		{"en": "flying press", "it": "schiacciatuffo"},
		{"en": "focus blast", "it": "focalcolpo"},
		{"en": "focus energy", "it": "focalenergia"},
		{"en": "focus punch", "it": "centripugno"},
		{"en": "follow me", "it": "sonoqui"},
		{"en": "force palm", "it": "palmoforza"},
		{"en": "foresight", "it": "preveggenza"},
		{"en": "forest's curse", "it": "boscomalocchio"},
		{"en": "foul play", "it": "ripicca"},
		{"en": "freeze shock", "it": "elettrogelo"},
		{"en": "freeze-dry", "it": "liofilizzazione"},
		{"en": "frenzy plant", "it": "radicalbero"},
		{"en": "frost breath", "it": "alitogelido"},
		{"en": "frustration", "it": "frustrazione"},
		{"en": "fury attack", "it": "furia"},
		{"en": "fury cutter", "it": "tagliofuria"},
		{"en": "fury swipes", "it": "sfuriate"},
		{"en": "fusion bolt", "it": "incrotuono"},
		{"en": "fusion flare", "it": "incrofiamma"},
		{"en": "future sight", "it": "divinazione"},
		{"en": "gastro acid", "it": "gastroacido"},
		{"en": "gear grind", "it": "ingracolpo"},
		{"en": "geomancy", "it": "geocontrollo"},
		{"en": "giga drain", "it": "gigassorbimento"},
		{"en": "giga impact", "it": "gigaimpatto"},
		{"en": "glaciate", "it": "gelamondo"},
		{"en": "glare", "it": "bagliore"},
		{"en": "grass knot", "it": "laccioerboso"},
		{"en": "grass pledge", "it": "erbapatto"},
		{"en": "grass whistle", "it": "meloderba"},
		{"en": "grassy terrain", "it": "campo erboso"},
		{"en": "gravity", "it": "gravità"},
		{"en": "growl", "it": "ruggito"},
		{"en": "growth", "it": "crescita"},
		{"en": "grudge", "it": "rancore"},
		{"en": "guard split", "it": "paridifesa"},
		{"en": "guard swap", "it": "barattoscudo"},
		{"en": "guillotine", "it": "ghigliottina"},
		{"en": "gunk shot", "it": "sporcolancio"},
		{"en": "gust", "it": "raffica"},
		{"en": "gyro ball", "it": "vortexpalla"},
		{"en": "hail", "it": "grandine"},
		{"en": "hammer arm", "it": "martelpugno"},
		{"en": "happy hour", "it": "cuccagna"},
		{"en": "harden", "it": "rafforzatore"},
		{"en": "haze", "it": "nube"},
		{"en": "head charge", "it": "ricciolata"},
		{"en": "head smash", "it": "zuccata"},
		{"en": "headbutt", "it": "bottintesta"},
		{"en": "heal bell", "it": "rintoccasana"},
		{"en": "heal block", "it": "anticura"},
		{"en": "heal order", "it": "comandocura"},
		{"en": "heal pulse", "it": "ondasana"},
		{"en": "healing wish", "it": "curardore"},
		{"en": "heart stamp", "it": "cuorestampo"},
		{"en": "heart swap", "it": "cuorbaratto"},
		{"en": "heat crash", "it": "marchiafuoco"},
		{"en": "heat wave", "it": "ondacalda"},
		{"en": "heavy slam", "it": "pesobomba"},
		{"en": "helping hand", "it": "altruismo"},
		{"en": "hex", "it": "sciagura"},
		{"en": "hidden power", "it": "introforza"},
		{"en": "high jump kick", "it": "calcinvolo"},
		{"en": "hold back", "it": "riguardo"},
		{"en": "hold hands", "it": "mano nella mano"},
		{"en": "hone claws", "it": "unghiaguzze"},
		{"en": "horn attack", "it": "incornata"},
		{"en": "horn drill", "it": "perforcorno"},
		{"en": "horn leech", "it": "legnicorno"},
		{"en": "howl", "it": "gridodilotta"},
		{"en": "hurricane", "it": "tifone"},
		{"en": "hydro cannon", "it": "idrocannone"},
		{"en": "hydro pump", "it": "idropompa"},
		{"en": "hyper beam", "it": "iper raggio"},
		{"en": "hyper fang", "it": "iperzanna"},
		{"en": "hyper voice", "it": "granvoce"},
		{"en": "hyperspace hole", "it": "forodimensionale"},
		{"en": "hyperspace fury", "it": "urtodimensionale"},
		{"en": "hypnosis", "it": "ipnosi"},
		{"en": "ice ball", "it": "palla gelo"},
		{"en": "ice beam", "it": "geloraggio"},
		{"en": "ice burn", "it": "vampagelida"},
		{"en": "ice fang", "it": "gelodenti"},
		{"en": "ice punch", "it": "gelopugno"},
		{"en": "ice shard", "it": "geloscheggia"},
		{"en": "icicle crash", "it": "scagliagelo"},
		{"en": "icicle spear", "it": "gelolancia"},
		{"en": "icy wind", "it": "ventogelato"},
		{"en": "imprison", "it": "esclusiva"},
		{"en": "incinerate", "it": "bruciatutto"},
		{"en": "inferno", "it": "marchiatura"},
		{"en": "infestation", "it": "assillo"},
		{"en": "ingrain", "it": "radicamento"},
		{"en": "ion deluge", "it": "pioggiaplasma"},
		{"en": "iron defense", "it": "ferroscudo"},
		{"en": "iron head", "it": "metaltestata"},
		{"en": "iron tail", "it": "codacciaio"},
		{"en": "judgment", "it": "giudizio"},
		{"en": "jump kick", "it": "calciosalto"},
		{"en": "karate chop", "it": "colpokarate"},
		{"en": "kinesis", "it": "cinèsi"},
		{"en": "king's shield", "it": "scudo reale"},
		{"en": "knock off", "it": "privazione"},
		{"en": "land's wrath", "it": "forza tellurica"},
		{"en": "last resort", "it": "ultimascelta"},
		{"en": "lava plume", "it": "lavasbuffo"},
		{"en": "leaf blade", "it": "fendifoglia"},
		{"en": "leaf storm", "it": "verdebufera"},
		{"en": "leaf tornado", "it": "vorticerba"},
		{"en": "leech life", "it": "sanguisuga"},
		{"en": "leech seed", "it": "parassiseme"},
		{"en": "leer", "it": "fulmisguardo"},
		{"en": "lick", "it": "leccata"},
		{"en": "light of ruin", "it": "luce nefasta"},
		{"en": "light screen", "it": "schermoluce"},
		{"en": "lock-on", "it": "localizza"},
		{"en": "lovely kiss", "it": "demonbacio"},
		{"en": "low kick", "it": "colpo basso"},
		{"en": "low sweep", "it": "calciobasso"},
		{"en": "lucky chant", "it": "fortuncanto"},
		{"en": "lunar dance", "it": "lunardanza"},
		{"en": "luster purge", "it": "abbagliante"},
		{"en": "mach punch", "it": "pugnorapido"},
		{"en": "magic coat", "it": "magivelo"},
		{"en": "magic room", "it": "magicozona"},
		{"en": "magical leaf", "it": "fogliamagica"},
		{"en": "magma storm", "it": "magmaclisma"},
		{"en": "magnet bomb", "it": "bombagnete"},
		{"en": "magnet rise", "it": "magnetascesa"},
		{"en": "magnetic flux", "it": "controllo polare"},
		{"en": "magnitude", "it": "magnitudo"},
		{"en": "mat block", "it": "ribaltappeto"},
		{"en": "me first", "it": "precedenza"},
		{"en": "mean look", "it": "malosguardo"},
		{"en": "meditate", "it": "meditazione"},
		{"en": "mega drain", "it": "megassorbimento"},
		{"en": "mega kick", "it": "megacalcio"},
		{"en": "mega punch", "it": "megapugno"},
		{"en": "megahorn", "it": "megacorno"},
		{"en": "memento", "it": "memento"},
		{"en": "metal burst", "it": "metalscoppio"},
		{"en": "metal claw", "it": "ferrartigli"},
		{"en": "metal sound", "it": "ferrostrido"},
		{"en": "meteor mash", "it": "meteorpugno"},
		{"en": "metronome", "it": "metronomo"},
		{"en": "milk drink", "it": "buonlatte"},
		{"en": "mimic", "it": "mimica"},
		{"en": "mind reader", "it": "leggimente"},
		{"en": "minimize", "it": "minimizzato"},
		{"en": "miracle eye", "it": "miracolvista"},
		{"en": "mirror coat", "it": "specchiovelo"},
		{"en": "mirror move", "it": "speculmossa"},
		{"en": "mirror shot", "it": "cristalcolpo"},
		{"en": "mist ball", "it": "foschisfera"},
		{"en": "mist", "it": "nebbia"},
		{"en": "misty terrain", "it": "campo nebbioso"},
		{"en": "moonblast", "it": "forza lunare"},
		{"en": "moonlight", "it": "lucelunare"},
		{"en": "morning sun", "it": "mattindoro"},
		{"en": "mud bomb", "it": "pantanobomba"},
		{"en": "mud shot", "it": "colpodifango"},
		{"en": "mud sport", "it": "fangata"},
		{"en": "mud-slap", "it": "fangosberla"},
		{"en": "muddy water", "it": "fanghiglia"},
		{"en": "mystical fire", "it": "magifiamma"},
		{"en": "nasty plot", "it": "congiura"},
		{"en": "natural gift", "it": "dononaturale"},
		{"en": "nature power", "it": "naturforza"},
		{"en": "needle arm", "it": "pugnospine"},
		{"en": "night daze", "it": "urtoscuro"},
		{"en": "night shade", "it": "ombra notturna"},
		{"en": "night slash", "it": "nottesferza"},
		{"en": "nightmare", "it": "incubo"},
		{"en": "noble roar", "it": "urlo"},
		{"en": "nuzzle", "it": "elettrococcola"},
		{"en": "oblivion wing", "it": "ali del fato"},
		{"en": "octazooka", "it": "octazooka"},
		{"en": "odor sleuth", "it": "segugio"},
		{"en": "ominous wind", "it": "funestovento"},
		{"en": "origin pulse", "it": "primopulsar"},
		{"en": "outrage", "it": "oltraggio"},
		{"en": "overheat", "it": "vampata"},
		{"en": "pain split", "it": "malcomune"},
		{"en": "parabolic charge", "it": "caricaparabola"},
		{"en": "parting shot", "it": "monito"},
		{"en": "pay day", "it": "giornopaga"},
		{"en": "payback", "it": "rivincita"},
		{"en": "peck", "it": "beccata"},
		{"en": "perish song", "it": "ultimocanto"},
		{"en": "petal blizzard", "it": "fiortempesta"},
		{"en": "petal dance", "it": "petalodanza"},
		{"en": "phantom force", "it": "spettrotuffo"},
		{"en": "pin missile", "it": "missilspillo"},
		{"en": "play nice", "it": "simpatia"},
		{"en": "play rough", "it": "carineria"},
		{"en": "pluck", "it": "spennata"},
		{"en": "poison fang", "it": "velenodenti"},
		{"en": "poison gas", "it": "velenogas"},
		{"en": "poison jab", "it": "velenpuntura"},
		{"en": "poison powder", "it": "velenpolvere"},
		{"en": "poison sting", "it": "velenospina"},
		{"en": "poison tail", "it": "velenocoda"},
		{"en": "pound", "it": "botta"},
		{"en": "powder snow", "it": "polneve"},
		{"en": "powder", "it": "pulviscoppio"},
		{"en": "power gem", "it": "gemmoforza"},
		{"en": "power split", "it": "pariattacco"},
		{"en": "power swap", "it": "barattoforza"},
		{"en": "power trick", "it": "ingannoforza"},
		{"en": "power whip", "it": "vigorcolpo"},
		{"en": "power-up punch", "it": "crescipugno"},
		{"en": "precipice blades", "it": "spade telluriche"},
		{"en": "present", "it": "regalino"},
		{"en": "protect", "it": "protezione"},
		{"en": "psybeam", "it": "psicoraggio"},
		{"en": "psych up", "it": "psicamisù"},
		{"en": "psychic", "it": "psichico"},
		{"en": "psycho boost", "it": "psicoslancio"},
		{"en": "psycho cut", "it": "psicotaglio"},
		{"en": "psycho shift", "it": "psicotrasfer"},
		{"en": "psyshock", "it": "psicoshock"},
		{"en": "psystrike", "it": "psicobotta"},
		{"en": "psywave", "it": "psiconda"},
		{"en": "punishment", "it": "punizione"},
		{"en": "pursuit", "it": "inseguimento"},
		{"en": "quash", "it": "spintone"},
		{"en": "quick attack", "it": "attacco rapido"},
		{"en": "quick guard", "it": "anticipo"},
		{"en": "quiver dance", "it": "eledanza"},
		{"en": "rage powder", "it": "polverabbia"},
		{"en": "rage", "it": "ira"},
		{"en": "rain dance", "it": "pioggiadanza"},
		{"en": "rapid spin", "it": "rapigiro"},
		{"en": "razor leaf", "it": "foglielama"},
		{"en": "razor shell", "it": "conchilama"},
		{"en": "razor wind", "it": "ventagliente"},
		{"en": "recover", "it": "ripresa"},
		{"en": "recycle", "it": "riciclo"},
		{"en": "reflect type", "it": "riflettipo"},
		{"en": "reflect", "it": "riflesso"},
		{"en": "refresh", "it": "rinfrescata"},
		{"en": "relic song", "it": "cantoantico"},
		{"en": "rest", "it": "riposo"},
		{"en": "retaliate", "it": "nemesi"},
		{"en": "return", "it": "ritorno"},
		{"en": "revenge", "it": "vendetta"},
		{"en": "reversal", "it": "contropiede"},
		{"en": "roar of time", "it": "fragortempo"},
		{"en": "roar", "it": "boato"},
		{"en": "rock blast", "it": "cadutamassi"},
		{"en": "rock climb", "it": "scalaroccia"},
		{"en": "rock polish", "it": "lucidatura"},
		{"en": "rock slide", "it": "frana"},
		{"en": "rock smash", "it": "spaccaroccia"},
		{"en": "rock throw", "it": "sassata"},
		{"en": "rock tomb", "it": "rocciotomba"},
		{"en": "rock wrecker", "it": "devastomasso"},
		{"en": "role play", "it": "giocodiruolo"},
		{"en": "rolling kick", "it": "calciorullo"},
		{"en": "rollout", "it": "rotolamento"},
		{"en": "roost", "it": "trespolo"},
		{"en": "rototiller", "it": "aracampo"},
		{"en": "round", "it": "coro"},
		{"en": "sacred fire", "it": "magifuoco"},
		{"en": "sacred sword", "it": "spadasolenne"},
		{"en": "safeguard", "it": "salvaguardia"},
		{"en": "sand attack", "it": "turbosabbia"},
		{"en": "sand tomb", "it": "sabbiotomba"},
		{"en": "sandstorm", "it": "terrempesta"},
		{"en": "scald", "it": "idrovampata"},
		{"en": "scary face", "it": "visotruce"},
		{"en": "scratch", "it": "graffio"},
		{"en": "screech", "it": "stridio"},
		{"en": "searing shot", "it": "sparafuoco"},
		{"en": "secret power", "it": "forzasegreta"},
		{"en": "secret sword", "it": "spadamistica"},
		{"en": "seed bomb", "it": "semebomba"},
		{"en": "seed flare", "it": "infuriaseme"},
		{"en": "seismic toss", "it": "movimento sismico"},
		{"en": "self-destruct", "it": "autodistruzione"},
		{"en": "shadow ball", "it": "palla ombra"},
		{"en": "shadow claw", "it": "ombrartigli"},
		{"en": "shadow force", "it": "oscurotuffo"},
		{"en": "shadow punch", "it": "pugnodombra"},
		{"en": "shadow sneak", "it": "furtivombra"},
		{"en": "sharpen", "it": "affilatore"},
		{"en": "sheer cold", "it": "purogelo"},
		{"en": "shell smash", "it": "gettaguscio"},
		{"en": "shift gear", "it": "cambiomarcia"},
		{"en": "shock wave", "it": "ondashock"},
		{"en": "signal beam", "it": "segnoraggio"},
		{"en": "silver wind", "it": "ventargenteo"},
		{"en": "simple beam", "it": "ondisinvolta"},
		{"en": "sing", "it": "canto"},
		{"en": "sketch", "it": "schizzo"},
		{"en": "skill swap", "it": "baratto"},
		{"en": "skull bash", "it": "capocciata"},
		{"en": "sky attack", "it": "aeroattacco"},
		{"en": "sky drop", "it": "cadutalibera"},
		{"en": "sky uppercut", "it": "stramontante"},
		{"en": "slack off", "it": "pigro"},
		{"en": "slam", "it": "schianto"},
		{"en": "slash", "it": "lacerazione"},
		{"en": "sleep powder", "it": "sonnifero"},
		{"en": "sleep talk", "it": "sonnolalia"},
		{"en": "sludge bomb", "it": "fangobomba"},
		{"en": "sludge wave", "it": "fangonda"},
		{"en": "sludge", "it": "fango"},
		{"en": "smack down", "it": "abbattimento"},
		{"en": "smelling salts", "it": "maniereforti"},
		{"en": "smog", "it": "smog"},
		{"en": "smokescreen", "it": "muro di fumo"},
		{"en": "snarl", "it": "urlorabbia"},
		{"en": "snatch", "it": "scippo"},
		{"en": "snore", "it": "russare"},
		{"en": "soak", "it": "inondazione"},
		{"en": "soft-boiled", "it": "covauova"},
		{"en": "solar beam", "it": "solarraggio"},
		{"en": "sonic boom", "it": "sonicboom"},
		{"en": "spacial rend", "it": "fendispazio"},
		{"en": "spark", "it": "scintilla"},
		{"en": "spider web", "it": "ragnatela"},
		{"en": "spike cannon", "it": "sparalance"},
		{"en": "spikes", "it": "punte"},
		{"en": "spiky shield", "it": "agodifesa"},
		{"en": "spit up", "it": "sfoghenergia"},
		{"en": "spite", "it": "dispetto"},
		{"en": "splash", "it": "splash"},
		{"en": "spore", "it": "spora"},
		{"en": "stealth rock", "it": "levitoroccia"},
		{"en": "steamroller", "it": "rulloduro"},
		{"en": "steel wing", "it": "alacciaio"},
		{"en": "sticky web", "it": "rete vischiosa"},
		{"en": "stockpile", "it": "accumulo"},
		{"en": "stomp", "it": "pestone"},
		{"en": "stone edge", "it": "pietrataglio"},
		{"en": "stored power", "it": "veicolaforza"},
		{"en": "storm throw", "it": "tempestretta"},
		{"en": "strength", "it": "forza"},
		{"en": "string shot", "it": "millebave"},
		{"en": "struggle bug", "it": "entomoblocco"},
		{"en": "struggle", "it": "scontro"},
		{"en": "stun spore", "it": "paralizzante"},
		{"en": "submission", "it": "sottomissione"},
		{"en": "substitute", "it": "sostituto"},
		{"en": "sucker punch", "it": "sbigoattacco"},
		{"en": "sunny day", "it": "giornodisole"},
		{"en": "super fang", "it": "superzanna"},
		{"en": "superpower", "it": "troppoforte"},
		{"en": "supersonic", "it": "supersuono"},
		{"en": "surf", "it": "surf"},
		{"en": "swagger", "it": "bullo"},
		{"en": "swallow", "it": "introenergia"},
		{"en": "sweet kiss", "it": "dolcebacio"},
		{"en": "sweet scent", "it": "profumino"},
		{"en": "swift", "it": "comete"},
		{"en": "switcheroo", "it": "rapidscambio"},
		{"en": "swords dance", "it": "danzaspada"},
		{"en": "synchronoise", "it": "sincrumore"},
		{"en": "synthesis", "it": "sintesi"},
		{"en": "tackle", "it": "azione"},
		{"en": "tail glow", "it": "codadiluce"},
		{"en": "tail slap", "it": "spazzasberla"},
		{"en": "tail whip", "it": "colpocoda"},
		{"en": "tailwind", "it": "ventoincoda"},
		{"en": "take down", "it": "riduttore"},
		{"en": "taunt", "it": "provocazione"},
		{"en": "techno blast", "it": "tecnobotto"},
		{"en": "teeter dance", "it": "strampadanza"},
		{"en": "telekinesis", "it": "telecinesi"},
		{"en": "teleport", "it": "teletrasporto"},
		{"en": "thief", "it": "furto"},
		{"en": "thrash", "it": "colpo"},
		{"en": "thousand arrows", "it": "mille frecce"},
		{"en": "thousand waves", "it": "mille onde"},
		{"en": "thunder fang", "it": "fulmindenti"},
		{"en": "thunder punch", "it": "tuonopugno"},
		{"en": "thunder shock", "it": "tuonoshock"},
		{"en": "thunder wave", "it": "tuononda"},
		{"en": "thunder", "it": "tuono"},
		{"en": "thunderbolt", "it": "fulmine"},
		{"en": "tickle", "it": "solletico"},
		{"en": "topsy-turvy", "it": "sottosopra"},
		{"en": "torment", "it": "attaccalite"},
		{"en": "toxic spikes", "it": "fielepunte"},
		{"en": "toxic", "it": "tossina"},
		{"en": "transform", "it": "trasformazione"},
		{"en": "tri attack", "it": "tripletta"},
		{"en": "trick room", "it": "distortozona"},
		{"en": "trick", "it": "raggiro"},
		{"en": "trick-or-treat", "it": "halloween"},
		{"en": "triple kick", "it": "triplocalcio"},
		{"en": "trump card", "it": "asso"},
		{"en": "twineedle", "it": "doppio ago"},
		{"en": "twister", "it": "tornado"},
		{"en": "u-turn", "it": "retromarcia"},
		{"en": "uproar", "it": "baraonda"},
		{"en": "v-create", "it": "generatore v"},
		{"en": "vacuum wave", "it": "vuotonda"},
		{"en": "venom drench", "it": "velenotrappola"},
		{"en": "venoshock", "it": "velenoshock"},
		{"en": "vice grip", "it": "presa"},
		{"en": "vine whip", "it": "frustata"},
		{"en": "vital throw", "it": "vitaltiro"},
		{"en": "volt switch", "it": "invertivolt"},
		{"en": "volt tackle", "it": "locomovolt"},
		{"en": "wake-up slap", "it": "svegliopacca"},
		{"en": "water gun", "it": "pistolacqua"},
		{"en": "water pledge", "it": "acquapatto"},
		{"en": "water pulse", "it": "idropulsar"},
		{"en": "water shuriken", "it": "acqualame"},
		{"en": "water sport", "it": "docciascudo"},
		{"en": "water spout", "it": "zampillo"},
		{"en": "waterfall", "it": "cascata"},
		{"en": "weather ball", "it": "palla clima"},
		{"en": "whirlpool", "it": "mulinello"},
		{"en": "whirlwind", "it": "turbine"},
		{"en": "wide guard", "it": "bodyguard"},
		{"en": "wild charge", "it": "sprizzalampo"},
		{"en": "will-o-wisp", "it": "fuocofatuo"},
		{"en": "wing attack", "it": "attacco d'ala"},
		{"en": "wish", "it": "desiderio"},
		{"en": "withdraw", "it": "ritirata"},
		{"en": "wonder room", "it": "mirabilzona"},
		{"en": "wood hammer", "it": "mazzuolegno"},
		{"en": "work up", "it": "cuordileone"},
		{"en": "worry seed", "it": "affannoseme"},
		{"en": "wrap", "it": "avvolgibotta"},
		{"en": "wring out", "it": "strizzata"},
		{"en": "x-scissor", "it": "forbice x"},
		{"en": "yawn", "it": "sbadiglio"},
		{"en": "zap cannon", "it": "falcecannone"},
		{"en": "zen headbutt", "it": "cozzata zen"}
	],
	"item": [
		{"en": "absorb bulb", "it": "bulbo"},
		{"en": "adamant orb", "it": "adamasfera"},
		{"en": "air balloon", "it": "palloncino"},
		{"en": "amulet coin", "it": "monetamuleto"},
		{"en": "assault vest", "it": "corpetto assalto"},
		{"en": "berry juice", "it": " succo di bacca"},
		{"en": "berserk gene", "it": "gene furioso"},
		{"en": "big root", "it": "granradice"},
		{"en": "binding band", "it": "legafascia"},
		{"en": "black belt", "it": "cinturanera"},
		{"en": "black glasses", "it": "occhialineri"},
		{"en": "black sludge", "it": "fangopece"},
		{"en": "blue scarf", "it": "fascia blu"},
		{"en": "bright powder", "it": "luminpolvere"},
		{"en": "bug gem", "it": "bijoucoleot."},
		{"en": "burn drive", "it": "piromodulo"},
		{"en": "cell battery", "it": "ricaripila"},
		{"en": "charcoal", "it": "carbonella"},
		{"en": "chill drive", "it": "gelomodulo"},
		{"en": "choice band", "it": "bendascelta"},
		{"en": "choice scarf", "it": "stolascelta"},
		{"en": "choice specs", "it": "lentiscelta"},
		{"en": "cleanse tag", "it": "velopuro"},
		{"en": "damp rock", "it": "rocciaumida"},
		{"en": "dark gem", "it": "bijoubuio"},
		{"en": "deep sea scale", "it": "squamabissi"},
		{"en": "deep sea tooth", "it": "denteabissi"},
		{"en": "destiny knot", "it": "destincomune"},
		{"en": "douse drive", "it": "idromodulo"},
		{"en": "draco plate", "it": "lastradrakon"},
		{"en": "dragon fang", "it": "dentedidrago"},
		{"en": "dragon gem", "it": "bijoudrago"},
		{"en": "dragon scale", "it": "squama drago"},
		{"en": "dread plate", "it": "lastratimore"},
		{"en": "dubious disc", "it": "dubbiodisco"},
		{"en": "earth plate", "it": "lastrageo"},
		{"en": "eject button", "it": "pulsantefuga"},
		{"en": "electirizer", "it": "elettritore"},
		{"en": "electric gem", "it": "bijouelettro"},
		{"en": "everstone", "it": "pietrastante"},
		{"en": "eviolite", "it": "evolcondensa"},
		{"en": "exp, share", "it": "condividi esp,*"},
		{"en": "expert belt", "it": "abilcintura"},
		{"en": "fighting gem", "it": "bijoulotta"},
		{"en": "fire gem", "it": "bijoufuoco"},
		{"en": "fist plate", "it": "lastrapugno"},
		{"en": "flame orb", "it": "fiammosfera"},
		{"en": "flame plate", "it": "lastrarogo"},
		{"en": "float stone", "it": "pietralieve"},
		{"en": "flying gem", "it": "bijouvolante"},
		{"en": "focus band", "it": "bandana"},
		{"en": "focus sash", "it": "focalnastro"},
		{"en": "fresh water", "it": "acqua fresca"},
		{"en": "full incense", "it": "gonfioaroma"},
		{"en": "ghost gem", "it": "bijouspettro"},
		{"en": "grass gem", "it": "bijouerba"},
		{"en": "green scarf", "it": "fascia verde"},
		{"en": "grip claw", "it": "presartigli"},
		{"en": "griseous orb", "it": "grigiosfera"},
		{"en": "ground gem", "it": "bijouterra"},
		{"en": "hard stone", "it": "pietradura"},
		{"en": "heat rock", "it": "rocciacalda"},
		{"en": "ice gem", "it": "bijoughiac."},
		{"en": "icicle plate", "it": "lastragelo"},
		{"en": "icy rock", "it": "rocciafredda"},
		{"en": "insect plate", "it": "lastrabaco"},
		{"en": "iron ball", "it": "ferropalla"},
		{"en": "iron plate", "it": "lastraferro"},
		{"en": "king's rock", "it": "roccia di re"},
		{"en": "lagging tail", "it": "rallentocoda"},
		{"en": "lax incense", "it": "distraroma"},
		{"en": "leftovers", "it": "avanzi"},
		{"en": "lemonade", "it": "lemonsucco"},
		{"en": "life orb", "it": "assorbisfera"},
		{"en": "light ball", "it": "elettropalla"},
		{"en": "light clay", "it": "creta luce"},
		{"en": "luck incense", "it": "fortunaroma"},
		{"en": "lucky egg", "it": "fortunuovo"},
		{"en": "lucky punch", "it": "fortunpugno"},
		{"en": "lustrous orb", "it": "splendisfera"},
		{"en": "macho brace", "it": "crescicappa"},
		{"en": "magmarizer", "it": "magmatore"},
		{"en": "magnet", "it": "calamita"},
		{"en": "meadow plate", "it": "lastraprato"},
		{"en": "mental herb", "it": "mentalerba"},
		{"en": "metal coat", "it": "metalcoperta"},
		{"en": "metal powder", "it": "metalpolvere"},
		{"en": "metronome", "it": "plessimetro"},
		{"en": "mind plate", "it": "lastramente"},
		{"en": "miracle seed", "it": "miracolseme"},
		{"en": "moomoo milk", "it": "latte mumu"},
		{"en": "muscle band", "it": "muscolbanda"},
		{"en": "mystic water", "it": "acquamagica"},
		{"en": "never-melt ice", "it": "gelomai"},
		{"en": "normal gem", "it": "bijounormale"},
		{"en": "odd incense", "it": "bizzoaroma"},
		{"en": "pink bow", "it": "fiocco rosa"},
		{"en": "pink scarf", "it": "fascia rosa"},
		{"en": "poison barb", "it": "velenago"},
		{"en": "poison gem", "it": "bijouveleno"},
		{"en": "polkadot bow", "it": "fiocco pois"},
		{"en": "power anklet", "it": "vigorgliera"},
		{"en": "power band", "it": "vigorbanda"},
		{"en": "power belt", "it": "vigorfascia"},
		{"en": "power bracer", "it": "vigorcerchio"},
		{"en": "power herb", "it": "vigorerba"},
		{"en": "power lens", "it": "vigorlente"},
		{"en": "power weight", "it": "vigorpeso"},
		{"en": "prism scale", "it": "squama bella"},
		{"en": "protector", "it": "copertura"},
		{"en": "psychic gem", "it": "bijoupsico"},
		{"en": "pure incense", "it": "puroaroma"},
		{"en": "quick claw", "it": "rapidartigli"},
		{"en": "quick powder", "it": "velopolvere"},
		{"en": "razor claw", "it": "affilartigli"},
		{"en": "razor fang", "it": "affilodente"},
		{"en": "reaper cloth", "it": "terrorpanno"},
		{"en": "red card", "it": "cartelrosso"},
		{"en": "red scarf", "it": "fascia rossa"},
		{"en": "ring target", "it": "facilsaglio"},
		{"en": "rock gem", "it": "bijouroccia"},
		{"en": "rock incense", "it": "roccioaroma"},
		{"en": "rocky helmet", "it": "bitorzolelmo"},
		{"en": "rose incense", "it": "rosaroma"},
		{"en": "safety goggles", "it": "visierantisabbia"},
		{"en": "scope lens", "it": "mirino"},
		{"en": "sea incense", "it": "marearoma"},
		{"en": "sharp beak", "it": "beccaffilato"},
		{"en": "shed shell", "it": "disfoguscio"},
		{"en": "shell bell", "it": "conchinella"},
		{"en": "shock drive", "it": "voltmodulo"},
		{"en": "silk scarf", "it": "sciarpaseta"},
		{"en": "silver powder", "it": "argenpolvere"},
		{"en": "sky plate", "it": "lastracielo"},
		{"en": "smoke ball", "it": "palla fumo"},
		{"en": "smooth rock", "it": "roccialiscia"},
		{"en": "snowball", "it": "palla di neve"},
		{"en": "soda pop", "it": "gassosa"},
		{"en": "soft sand", "it": "sabbiasoffice"},
		{"en": "soothe bell", "it": "calmanella"},
		{"en": "soul dew", "it": "cuorugiada"},
		{"en": "spell tag", "it": "spettrotarga"},
		{"en": "splash plate", "it": "lastraidro"},
		{"en": "spooky plate", "it": "lastratetra"},
		{"en": "steel gem", "it": "bijouacciaio"},
		{"en": "stick", "it": "gambo"},
		{"en": "sticky barb", "it": "vischiopunta"},
		{"en": "stone plate", "it": "lastrapietra"},
		{"en": "tea", "it": "tè"},
		{"en": "thick club", "it": "ossospesso"},
		{"en": "toxic orb", "it": "tossicsfera"},
		{"en": "toxic plate", "it": "lastrafiele"},
		{"en": "twisted spoon", "it": "cucchiaiotorto"},
		{"en": "up-grade", "it": "upgrade"},
		{"en": "water gem", "it": "bijouacqua"},
		{"en": "wave incense", "it": "ondaroma"},
		{"en": "weakness policy", "it": "vulneropolizza"},
		{"en": "whipped dream", "it": "dolcespuma"},
		{"en": "white herb", "it": "erbachiara"},
		{"en": "wide lens", "it": "grandelente"},
		{"en": "wise glasses", "it": "saviocchiali"},
		{"en": "yellow scarf", "it": "fascia gialla"},
		{"en": "zap plate", "it": "lastrasaetta"},
		{"en": "zoom lens", "it": "zoomlente"}
	],
	"berry": [
		{"en": "aguav berry", "it": "baccaguava"},
		{"en": "apicot berry", "it": "baccacocca"},
		{"en": "aspear berry", "it": "baccaperina"},
		{"en": "babiri berry", "it": "baccababiri"},
		{"en": "belue berry", "it": "baccartillo"},
		{"en": "bluk berry", "it": "baccamora"},
		{"en": "charti berry", "it": "baccaciofo"},
		{"en": "cheri berry", "it": "baccaliegia"},
		{"en": "chesto berry", "it": "baccastagna"},
		{"en": "chilan berry", "it": "baccacinlan"},
		{"en": "chople berry", "it": "baccarosmel"},
		{"en": "coba berry", "it": "baccababa"},
		{"en": "colbur berry", "it": "baccaxan"},
		{"en": "cornn berry", "it": "baccavena"},
		{"en": "custap berry", "it": "baccacrela"},
		{"en": "durin berry", "it": "baccadurian"},
		{"en": "enigma berry", "it": "baccaenigma"},
		{"en": "figy berry", "it": "baccafico"},
		{"en": "ganlon berry", "it": "baccalongan"},
		{"en": "grepa berry", "it": "baccauva"},
		{"en": "haban berry", "it": "baccahaban"},
		{"en": "hondew berry", "it": "baccamelon"},
		{"en": "iapapa berry", "it": "baccapaia"},
		{"en": "jaboca berry", "it": "baccajaba"},
		{"en": "kasib berry", "it": "baccacitrus"},
		{"en": "kebia berry", "it": "baccakebia"},
		{"en": "kee berry", "it": "baccalighia"},
		{"en": "kelpsy berry", "it": "baccalga"},
		{"en": "lansat berry", "it": "baccalangsa"},
		{"en": "leppa berry", "it": "baccamela"},
		{"en": "liechi berry", "it": "baccalici"},
		{"en": "lum berry", "it": "baccaprugna"},
		{"en": "mago berry", "it": "baccamango"},
		{"en": "magost berry", "it": "baccagostan"},
		{"en": "maranga berry", "it": "baccapane"},
		{"en": "micle berry", "it": "baccaracolo"},
		{"en": "nanab berry", "it": "baccabana"},
		{"en": "nomel berry", "it": "baccalemon"},
		{"en": "occa berry", "it": "baccacao"},
		{"en": "oran berry", "it": "baccarancia"},
		{"en": "pamtre berry", "it": "baccapalma"},
		{"en": "passho berry", "it": "baccapasflo"},
		{"en": "payapa berry", "it": "baccapayapa"},
		{"en": "pecha berry", "it": "baccapesca"},
		{"en": "persim berry", "it": "baccaki"},
		{"en": "petaya berry", "it": "baccapitaya"},
		{"en": "pinap berry", "it": "baccananas"},
		{"en": "pomeg berry", "it": "baccagrana"},
		{"en": "qualot berry", "it": "baccaloquat"},
		{"en": "rabuta berry", "it": "baccambutan"},
		{"en": "rawst berry", "it": "baccafrago"},
		{"en": "razz berry", "it": "baccalampon"},
		{"en": "rindo berry", "it": "baccarindo"},
		{"en": "roseli berry", "it": "baccarcadè"},
		{"en": "rowap berry", "it": "baccaroam"},
		{"en": "salac berry", "it": "baccasalak"},
		{"en": "shuca berry", "it": "baccanaca"},
		{"en": "sitrus berry", "it": "baccacedro"},
		{"en": "spelon berry", "it": "baccamelos"},
		{"en": "starf berry", "it": "baccambola"},
		{"en": "tamato berry", "it": "baccamodoro"},
		{"en": "tanga berry", "it": "baccaitan"},
		{"en": "wacan berry", "it": "baccaparmen"},
		{"en": "watmel berry", "it": "baccacomero"},
		{"en": "wepear berry", "it": "baccapera"},
		{"en": "wiki berry", "it": "baccaprugna"},
		{"en": "yache berry", "it": "baccamoya"}
	]/*,
	"megastone" : [
		{"en": "abomasite", "it": "abomasnowite"},
		{"en": "absolite", "it": "absolite"},
		{"en": "aerodactylite", "it": "aerodactylite"},
		{"en": "aggronite", "it": "aggronite"},
		{"en": "alakazite", "it": "alakazamite"},
		{"en": "altarianite", "it": "altarite"}
		{"en": "ampharosite", "it": "ampharosite"},
		{"en": "audinite", "it": "audinite"}
		{"en": "banettite", "it": "banettite"},
		{"en": "beedrillite", "it": "beedrillite"}
		{"en": "blastoisinite", "it": "blastoisite"},
		{"en": "blazikenite", "it": "blazikenite"},
		{"en": "cameruptite", "it": "cameruptite"}
		{"en": "charizardite x", "it": "charizardite x"},
		{"en": "charizardite y", "it": "charizardite y"},
		{"en": "diancite", "it": "diancite"},
		{"en": "galladite", "it": "galladite"}
		{"en": "garchompite", "it": "garchompite"},
		{"en": "gardevoirite", "it": "gardevoirite"},
		{"en": "gengarite", "it": "gengarite"},
		{"en": "glalitite", "it": "glalite"},
		{"en": "gyaradosite", "it": "gyaradosite"},
		{"en": "heracronite", "it": "heracrossite"},
		{"en": "houndoominite", "it": "houndoomite"},
		{"en": "kangaskhanite", "it": "kangaskhanite"},
		{"en": "latiasite", "it": "latiasite"},
		{"en": "latiosite", "it": "latiosite"},
		{"en": "lopunnite", "it": "lopunnite"}
		{"en": "lucarionite", "it": "lucarite"},
		{"en": "manectite", "it": "manectricite"},
		{"en": "mawilite", "it": "mawilite"},
		{"en": "medichamite", "it": "medichamite"},
		{"en": "metagrossite", "it": "metagrossite"},
		{"en": "mewtwonite x", "it": "mewtwoite x"},
		{"en": "mewtwonite y", "it": "mewtwoite y"},
		{"en": "pidgeotite", "it": "pidgeotite"}
		{"en": "pinsirite", "it": "pinsirite"},
		{"en": "sablenite", "it": "sableyeite"}
		{"en": "salamencite", "it": "salamencite"}
		{"en": "sceptilite", "it": "sceptilite"},
		{"en": "scizorite", "it": "scizorite"},
		{"en": "sharpedonite", "it": "sharpedite"}
		{"en": "slowbronite", "it": "slowbroite"}
		{"en": "steelixite", "it": "steelixite"},
		{"en": "swampertite", "it": "swampertite"},
		{"en": "tyranitarite", "it": "tyranitarite"},
		{"en": "venusaurite", "it": "venusaurite"}
	]*/,
	"nature": [
		{"en": "adamant", "it": "decisa"},
		{"en": "bashful", "it": "ritrosa"},
		{"en": "bold", "it": "sicura"},
		{"en": "brave", "it": "audace"},
		{"en": "calm", "it": "calma"},
		{"en": "careful", "it": "cauta"},
		{"en": "docile", "it": "docile"},
		{"en": "gentle", "it": "gentile"},
		{"en": "hardy", "it": "ardita"},
		{"en": "hasty", "it": "lesta"},
		{"en": "impish", "it": "scaltra"},
		{"en": "jolly", "it": "allegra"},
		{"en": "lax", "it": "fiacca"},
		{"en": "lonely", "it": "schiva"},
		{"en": "mild", "it": "mite"},
		{"en": "modest", "it": "modesta"},
		{"en": "naive", "it": "ingenua"},
		{"en": "naughty", "it": "birbona"},
		{"en": "quiet", "it": "quieta"},
		{"en": "quirky", "it": "furba"},
		{"en": "rash", "it": "ardente"},
		{"en": "relaxed", "it": "placida"},
		{"en": "sassy", "it": "vivace"},
		{"en": "serious", "it": "seria"},
		{"en": "timid", "it": "timida"}
	]
};